Repository FAForever/downlords-faf-client, pull requests merged in 2018-05, with the labels that each got.

#885 search vault on enter in query bar
  src/main/resources/theme/vault/search/search.fxml
Labels: in progress, ready to be merged

#876 Make "query.contains" default selected comparison operator
  src/main/java/com/faforever/client/query/SpecificationController.java
Labels: in progress, ready to be merged

#870 Only notifies when specified
  src/main/java/com/faforever/client/player/FriendOnlineNotifier.java
  src/test/java/com/faforever/client/player/FriendOnlineNotifierTest.java
Labels: in progress, ready to be merged

#839 Exclude hidden maps/mods from vault query
  src/main/java/com/faforever/client/api/FafApiAccessorImpl.java
Labels: in progress, ready to be merged

#895 Make it mutable map
  src/main/java/com/faforever/client/preferences/Preferences.java
Labels: in progress, ready to be merged

#897 map vault, searchable properties: add downloads and play count
  src/main/java/com/faforever/client/preferences/VaultPrefs.java
  src/main/java/com/faforever/client/query/SearchableProperties.java
  src/main/resources/i18n/messages.properties
Labels: in progress, ready to be merged

#904 set posix uid executable permission
  src/main/java/com/faforever/client/legacy/PosixUidService.java
Labels: S5 trivial, in progress

#853 Try removing memory leaks
  .idea/codeStyles/codeStyleConfig.xml
  src/main/java/com/faforever/client/game/GameDetailController.java
  src/main/java/com/faforever/client/game/GameTooltipController.java
  src/main/java/com/faforever/client/game/TeamCardController.java
Labels: in progress

#914 Fix NPE during login
  src/main/java/com/faforever/client/main/MainController.java
Labels: in progress, ready to be merged
