Repository FAForever/downlords-faf-client, pull requests merged in 2018-03, with the labels that each got.

#793 Allow server properties to be configured on login
  .idea/modules/downlords-faf-client.iml
  build.gradle
  downlords-faf-client.install4j
  src/main/java/com/faforever/client/api/FafApiAccessorImpl.java
  src/main/java/com/faforever/client/config/ClientProperties.java
  src/main/java/com/faforever/client/login/LoginController.java
  src/main/java/com/faforever/client/remote/FafServerAccessorImpl.java
  src/main/java/com/faforever/client/replay/ReplayServer.java
  src/main/java/com/faforever/client/replay/ReplayServerImpl.java
  src/main/resources/application.yml
  src/main/resources/i18n/messages.properties
  src/main/resources/i18n/messages_de_DE.properties
  src/main/resources/theme/login.fxml
  src/test/java/com/faforever/client/login/LoginControllerTest.java
Labels: in progress

#795 Return empty String to avoid NullPointerException
  src/main/java/com/faforever/client/chat/UserInfoWindowController.java
Labels: in progress, ready to be merged

#716 Show the correct rating in replay detail
  src/main/java/com/faforever/client/game/PlayerCardTooltipController.java
  src/main/java/com/faforever/client/game/RatingType.java
  src/main/java/com/faforever/client/game/TeamCardController.java
  src/main/java/com/faforever/client/replay/ReplayDetailController.java
  src/test/java/com/faforever/client/game/TeamCardControllerTest.java
Labels: in progress, ready to be merged

#756 Fix mod download
  .gitignore
  src/main/java/com/faforever/client/api/FafApiAccessor.java
  src/main/java/com/faforever/client/api/FafApiAccessorImpl.java
  src/main/java/com/faforever/client/api/MockFafApiAccessor.java
  src/main/java/com/faforever/client/config/FeaturedModUpdaterConfig.java
  src/main/java/com/faforever/client/config/MockFeaturedModUpdaterConfig.java
  src/main/java/com/faforever/client/game/CreateGameController.java
  src/main/java/com/faforever/client/game/GameServiceImpl.java
  src/main/java/com/faforever/client/mod/Mod.java
  src/main/java/com/faforever/client/mod/ModCardController.java
  src/main/java/com/faforever/client/mod/ModDetailController.java
  src/main/java/com/faforever/client/mod/ModService.java
  src/main/java/com/faforever/client/mod/ModServiceImpl.java
  src/main/java/com/faforever/client/mod/ModUploadController.java
  src/main/java/com/faforever/client/mod/ModVaultController.java
  src/main/java/com/faforever/client/mod/ModVersion.java
  src/main/java/com/faforever/client/mod/UninstallModTask.java
  src/main/java/com/faforever/client/mod/event/ModUploadedEvent.java
  src/main/java/com/faforever/client/patch/BireusFeaturedModUpdateTask.java
  src/main/java/com/faforever/client/patch/GameUpdaterImpl.java
  src/main/java/com/faforever/client/patch/GitFeaturedModUpdateTaskImpl.java
  src/main/java/com/faforever/client/remote/FafService.java
  src/main/java/com/faforever/client/remote/FafServiceImpl.java
  src/main/resources/i18n/messages_de_DE.properties
  src/test/java/com/faforever/client/api/FafApiAccessorImplTest.java
  src/test/java/com/faforever/client/game/CreateGameControllerTest.java
  src/test/java/com/faforever/client/mod/ModCardControllerTest.java
  src/test/java/com/faforever/client/mod/ModDetailControllerTest.java
  src/test/java/com/faforever/client/mod/ModInfoBeanBuilder.java
  src/test/java/com/faforever/client/mod/ModServiceImplTest.java
  src/test/java/com/faforever/client/mod/ModUploadControllerTest.java
  src/test/java/com/faforever/client/mod/ModVaultControllerTest.java
  src/test/java/com/faforever/client/mod/UninstallModTaskTest.java
Labels: in progress, ready to be merged

#778 Fix that not corrupted replays are marked as corrupt
  src/main/java/com/faforever/client/api/FafApiAccessorImpl.java
  src/main/java/com/faforever/client/map/MapServiceImpl.java
  src/main/java/com/faforever/client/replay/ReplayServiceImpl.java
Labels: in progress, ready to be merged

#774 Fix replays show wrong game quality
  src/main/java/com/faforever/client/replay/ReplayCardController.java
  src/main/java/com/faforever/client/replay/ReplayDetailController.java
Labels: in progress

#773 Remake create game button
  src/main/java/com/faforever/client/chat/ChatController.java
  src/main/java/com/faforever/client/coop/CoopController.java
  src/main/java/com/faforever/client/fx/AbstractViewController.java
  src/main/java/com/faforever/client/game/CreateGameController.java
  src/main/java/com/faforever/client/game/CustomGamesController.java
  src/main/java/com/faforever/client/main/MainController.java
  src/main/java/com/faforever/client/main/event/HostGameEvent.java
  src/main/java/com/faforever/client/main/event/Open1v1Event.java
  src/main/java/com/faforever/client/main/event/OpenCoopEvent.java
  src/main/java/com/faforever/client/main/event/OpenCustomGamesEvent.java
  src/main/java/com/faforever/client/map/HostMapInCustomGameEvent.java
  src/main/java/com/faforever/client/map/MapDetailController.java
  src/main/java/com/faforever/client/play/PlayController.java
  src/main/resources/theme/play/play.fxml
Labels: in progress, ready to be merged

#808 Correct Main Class
  build.gradle
Labels: in progress, ready to be merged

#838 #821 hide install4j splash via reflection
  src/main/java/com/faforever/client/main/MainController.java
Labels: in progress, ready to be merged

#769 #767 copy username in chat
  src/main/java/com/faforever/client/chat/ChatUserContextMenuController.java
  src/main/resources/i18n/messages.properties
  src/main/resources/i18n/messages_de.properties
  src/main/resources/theme/chat/chat_user_context_menu.fxml
Labels: ready to be merged

#784 fixes #783, custom color for friends displayed correctly, allow color…
  src/main/java/com/faforever/client/chat/AbstractChatTabController.java
  src/main/java/com/faforever/client/chat/ChannelTabController.java
  src/main/java/com/faforever/client/chat/ChatUserContextMenuController.java
  src/main/java/com/faforever/client/chat/ChatUserItemController.java
Labels: in progress, ready to be merged

#842 Show player idle time in chat
  src/main/java/com/faforever/client/chat/ChatUserItemController.java
  src/main/resources/i18n/messages.properties
  src/main/resources/i18n/messages_de.properties
Labels: in progress, ready to be merged
